# Generated by Django 3.2.5 on 2021-08-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={'verbose_name': 'Product Specification Value', 'verbose_name_plural': 'Product Specification Values'},
        ),
    ]
